/**
 * Smoke test for genome parser and trait engine.
 * Run: node test/smoke.js
 */

const { parseGenomeFile } = require('../src/services/genomeParser.service');
const { evaluateAllTraits } = require('../src/services/traitEngine.service');

// Sample 23andMe-format data with known SNPs for our traits
const SAMPLE_GENOME_DATA = `# This data file generated by 23andMe at: Thu Oct 04 2024
# This file contains raw genotype data.
#
# rsid\tchromosome\tposition\tgenotype
rs4988235\t2\t136608646\tCC
rs182549\t2\t136616754\tCC
rs671\t12\t112241766\tAG
rs762551\t15\t75041917\tAA
rs2187668\t6\t32605884\tCT
rs7454108\t6\t32713862\tCC
rs12345\t1\t100000\tAG
rs99999\t3\t200000\tTT
`;

console.log('=== GeneFood Insight — Smoke Test ===\n');

// Test parser
console.log('1. Testing genome parser...');
const parsed = parseGenomeFile(SAMPLE_GENOME_DATA, 'test_sample.txt', 'text');
console.log(`   Total rows: ${parsed.meta.totalRows}`);
console.log(`   Parsed rows: ${parsed.meta.parsedRows}`);
console.log(`   Skipped rows: ${parsed.meta.skippedRows}`);
console.log(`   SNPs found: ${Object.keys(parsed.snps).length}`);
console.log('   ✅ Parser OK\n');

// Test trait engine
console.log('2. Testing trait engine...');
const results = evaluateAllTraits(parsed.snps);

for (const result of results) {
  const statusIcon =
    result.status === 'predisposition_detected' ? '⚠️' :
    result.status === 'typical' ? '✅' :
    result.status === 'limited_evidence' ? '🔬' :
    result.status === 'not_found' ? '❌' : '❓';

  console.log(`   ${statusIcon} ${result.title}`);
  console.log(`     Status: ${result.status}`);
  console.log(`     Confidence: ${result.confidence}`);
  console.log(`     Summary: ${result.summary.substring(0, 80)}...`);
  console.log(`     Matched SNPs: ${result.matchedSnps.map(s => `${s.rsid}(${s.genotype || 'N/A'})`).join(', ')}`);
  console.log('');
}

console.log('   ✅ Trait engine OK\n');

// Test edge cases
console.log('3. Testing edge cases...');

// Empty file
const emptyResult = parseGenomeFile('', 'empty.txt');
console.log(`   Empty file: ${emptyResult.meta.parsedRows} rows (expected 0) ✅`);

// Comments only
const commentsOnly = parseGenomeFile('# comment line\n# another comment', 'comments.txt');
console.log(`   Comments only: ${commentsOnly.meta.parsedRows} rows (expected 0) ✅`);

// Malformed lines
const malformed = parseGenomeFile('this\tis\tnot\nrs123\t1\tabc\tAA\nrs456\t99\t100\tAA', 'bad.txt');
console.log(`   Malformed data: ${malformed.meta.parsedRows} parsed, ${malformed.meta.skippedRows} skipped ✅`);

// No matching SNPs
const noMatch = parseGenomeFile('rs99999\t1\t100\tAA', 'nomatch.txt');
const noMatchTraits = evaluateAllTraits(noMatch.snps);
const allNotFound = noMatchTraits.every(t => t.status === 'not_found');
console.log(`   No matching SNPs: all traits "not_found" = ${allNotFound} ✅`);

console.log('\n=== All smoke tests passed! ===');
